### ISSUE TITLE
Broken Drawer in gh-page using chrome

### ISSUE THREAD

**Issue by dipsywong98** [IniZio/usthing-ui#4]
![image](https://user-images.githubusercontent.com/24851190/44411745-d06a3200-a599-11e8-8329-ebf75954a7fd.png)

can be fixed by adding z-index to the drawer

**Comment by dipsywong98** [comment]
💩 there are so many things are broken in the gh-page...

toolbar, table, editor, calendar...

**Comment by IniZio** [comment]
That the bugs of styleguidist :joy:

**Comment by dipsywong98** [comment]
lol 🤣

**Comment by IniZio** [comment]
@dipsywong98  Now all components except calendar and table should work in the doc?

**Comment by dipsywong98** [comment]
should be yes
